-- Supabase Database Schema for X Growth CRM Dashboard

-- 1. Activities Table
CREATE TABLE IF NOT EXISTS public.activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts TIMESTAMPTZ DEFAULT NOW(),
    action TEXT NOT NULL,
    handle TEXT,
    segment TEXT,
    variant TEXT,
    detail TEXT,
    result TEXT DEFAULT 'ok',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Prospects Table
CREATE TABLE IF NOT EXISTS public.prospects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    handle TEXT UNIQUE NOT NULL,
    name TEXT,
    url TEXT,
    segment TEXT DEFAULT 'founder',
    score INT DEFAULT 0,
    stage TEXT DEFAULT 'new',
    last_touch TIMESTAMPTZ,
    next_action_date TIMESTAMPTZ,
    touches INT DEFAULT 0,
    product_url TEXT,
    last_variant TEXT,
    outcome TEXT,
    notes TEXT,
    why TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Insights Table
CREATE TABLE IF NOT EXISTS public.insights (
    id INT PRIMARY KEY DEFAULT 1,
    content TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT single_row CHECK (id = 1)
);

-- Row Level Security (RLS) Policies (Enable read access for anon users)
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prospects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.insights ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anon read access to activities" ON public.activities FOR SELECT USING (true);
CREATE POLICY "Allow anon read access to prospects" ON public.prospects FOR SELECT USING (true);
CREATE POLICY "Allow anon read access to insights" ON public.insights FOR SELECT USING (true);

-- Allow service role / authenticated insert & update
CREATE POLICY "Allow write access to activities" ON public.activities FOR ALL USING (true);
CREATE POLICY "Allow write access to prospects" ON public.prospects FOR ALL USING (true);
CREATE POLICY "Allow write access to insights" ON public.insights FOR ALL USING (true);
