export default async function handler(req, res) {
  const supabaseUrl = process.env.SUPABASE_URL || "https://jwswpryozfxzaocimadp.supabase.co";
  const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY;
  const xUserToken = process.env.X_USER_ACCESS_TOKEN || "ZDdibjRaZHJ5Y1BQbDM2ei1jM01tOVZoazR1VVdMVDR4eTVkdjRHRGs0V3lxOjE3ODYzMDY3MzA4Nzg6MTowOmF0OjE";

  if (req.method === 'GET') {
    return res.status(200).json({ status: "Pitch MCP Webhook Receiver Active", url: "https://dashboard-blue-five-75.vercel.app/api/pitch-webhook" });
  }

  if (req.method === 'POST') {
    try {
      let body = req.body || {};
      if (typeof body === 'string') {
        try { body = JSON.parse(body); } catch (e) {}
      }

      const jobId = body.jobId || body.id;
      const status = body.status;
      const artifacts = body.artifacts || {};
      const s3Url = artifacts.final_with_cards || artifacts.video || body.s3_url || body.videoUrl || `https://trypitch.co/editor/${jobId}`;

      console.log(`========================================================================`);
      console.log(`[PITCH MCP WEBHOOK CALLBACK RECEIVED]`);
      console.log(`Job ID: ${jobId}`);
      console.log(`Status: ${status}`);
      console.log(`S3 Video URL: ${s3Url}`);
      console.log(`========================================================================`);

      if (jobId && (status === 'COMPLETED' || status === 'completed') && supabaseUrl && supabaseKey) {
        const headers = { 'apikey': supabaseKey, 'Authorization': `Bearer ${supabaseKey}`, 'Content-Type': 'application/json' };

        // 1. Fetch matching job from Supabase
        const fetchResp = await fetch(`${supabaseUrl}/rest/v1/mention_jobs?editor_job_id=eq.${encodeURIComponent(jobId)}`, { headers });
        if (fetchResp.ok) {
          const jobs = await fetchResp.json();
          if (jobs && jobs.length > 0) {
            const job = jobs[0];
            const tweetId = job.tweet_id;
            const userHandle = job.user_handle;

            // 2. Post X Reply if tweet_id is numeric
            let xReplyId = null;
            if (tweetId && /^\d+$/.test(tweetId)) {
              const replyText = `Here is your product demo ${userHandle} generated by @trypitchdotco! Hope you enjoy it: ${s3Url} 🎬`;
              try:
                const xResp = await fetch("https://api.twitter.com/2/tweets", {
                  method: "POST",
                  headers: {
                    "Authorization": `Bearer ${xUserToken}`,
                    "Content-Type": "application/json"
                  },
                  body: JSON.stringify({
                    text: replyText,
                    reply: { in_reply_to_tweet_id: tweetId }
                  })
                });
                if (xResp.ok) {
                  const xData = await xResp.json();
                  xReplyId = xData?.data?.id;
                  console.log(`[Pitch Webhook] Posted X reply ID ${xReplyId} for tweet ${tweetId}`);
                }
              } catch (xErr) {
                console.error("[Pitch Webhook X Reply Error]:", xErr);
              }
            }

            // 3. Update Supabase mention_job to delivered
            await fetch(`${supabaseUrl}/rest/v1/mention_jobs?id=eq.${job.id}`, {
              method: 'PATCH',
              headers,
              body: JSON.stringify({
                status: 'delivered',
                s3_video_url: s3Url,
                x_reply_id: xReplyId || job.x_reply_id
              })
            }).catch(err => console.error("[Pitch Webhook Supabase Update Error]:", err));
          }
        }
      }

      return res.status(200).json({ status: "ok", received_job_id: jobId });
    } catch (err) {
      console.error("[Pitch Webhook Callback Error]:", err);
      return res.status(500).json({ error: err.message });
    }
  }

  return res.status(405).json({ error: "Method not allowed" });
}
