use crate::{
    db::Database,
    pitch_mcp::{extract_s3_url, get_job_status, get_launch_video_status},
    x_api::XApiClient,
};

pub async fn advance_rendering_queue(dry_run: bool, limit: usize) -> Result<usize, String> {
    println!("=== [TRIGGERED DEMO VIDEO DELIVERY WORKER] ===");

    let db = Database::open().map_err(|e| format!("DB Error: {}", e))?;
    let mut x_client = XApiClient::new();

    let rendering_jobs = db
        .get_mention_jobs_by_status(Some("rendering"), limit)
        .map_err(|e| e.to_string())?;
    let submitted_jobs = db
        .get_mention_jobs_by_status(Some("submitted"), limit)
        .map_err(|e| e.to_string())?;

    let mut active_jobs = rendering_jobs;
    active_jobs.extend(submitted_jobs);

    println!(
        "[Worker] Found {} active rendering jobs in SQLite DB.",
        active_jobs.len()
    );

    let mut delivered_count = 0;

    for mut job in active_jobs {
        let job_id = job.editor_job_id.clone().unwrap_or_default();
        let user_handle = job.user_handle.clone();
        let tweet_id = job.tweet_id.clone();
        let target_url = job.target_url.clone();

        if job_id.is_empty() {
            continue;
        }

        println!("\n--------------------------------------------------");
        println!("[CHECKING RENDER STATUS] Pitch MCP Job ID: {}", job_id);
        println!("Target User: {}", user_handle);
        println!("Product URL: {}", target_url);

        let (mcp_status, s3_url) = if job_id.starts_with("launch:") {
            let proj_name = &job_id[7..];
            match get_launch_video_status(proj_name).await {
                Ok(mcp_res) => {
                    let has_video = mcp_res["hasVideo"].as_bool().unwrap_or(false) || mcp_res["videoUrl"].as_str().is_some();
                    let url = extract_s3_url(&mcp_res);
                    if has_video && !url.is_empty() {
                        ("COMPLETED".to_string(), url)
                    } else {
                        ("PROCESSING".to_string(), String::new())
                    }
                }
                Err(e) => {
                    println!("[Worker Launch MCP Error]: {}", e);
                    ("PROCESSING".to_string(), String::new())
                }
            }
        } else {
            match get_job_status(&job_id).await {
                Ok(mcp_res) => {
                    let st = mcp_res["status"].as_str().unwrap_or_default().to_string();
                    let url = extract_s3_url(&mcp_res);
                    (st, url)
                }
                Err(e) => {
                    println!("[Worker MCP Error] Could not query job {}: {}", job_id, e);
                    ("ERROR".to_string(), String::new())
                }
            }
        };

        println!("[Pitch MCP Status]: {}", mcp_status);

        if mcp_status == "COMPLETED" {
            if s3_url.is_empty() {
                println!("⚠️ [Worker Warning] COMPLETED status but no S3 MP4 videoUrl found in MCP response!");
                continue;
            }

            println!("🎉 [VIDEO RENDERING COMPLETED] S3 URL: {}", s3_url);

            let is_launch = job_id.starts_with("launch:") || job.tweet_id.to_lowercase().contains("launch") || job.target_url.to_lowercase().contains("launch");
            let reply_text = if is_launch {
                format!(
                    "Here is your launch video {} generated by @trypitchdotco! Hope you enjoy it: {} 🚀",
                    user_handle, s3_url
                )
            } else {
                format!(
                    "Here is your product demo {} generated by @trypitchdotco! Hope you enjoy it: {} 🎬",
                    user_handle, s3_url
                )
            };

                    if dry_run {
                        println!("[DRY RUN] Would post reply: {}", reply_text);
                        continue;
                    }

                    let mut reply_id = String::new();
                    if !tweet_id.is_empty() {
                        match x_client.post_tweet(&reply_text, Some(&tweet_id)).await {
                            Ok(rid) => {
                                println!("[X Delivery Reply Sent] Reply Tweet ID: {}", rid);
                                reply_id = rid;
                            }
                            Err(e) => println!("[Worker X Reply Error]: {}", e),
                        }
                    }

                    job.status = "delivered".to_string();
                    job.s3_video_url = Some(s3_url);
                    job.x_reply_id = Some(reply_id);

                    let _ = db.upsert_mention_job(&job);
                    delivered_count += 1;
                } else if mcp_status == "FAILED" || mcp_status == "ERROR" {
                    println!("❌ [VIDEO RENDERING FAILED] Job ID: {}", job_id);
                    job.status = "failed".to_string();
                    let _ = db.upsert_mention_job(&job);
                }
    }

    println!(
        "\n=== [WORKER COMPLETE] Total Delivered: {} ===",
        delivered_count
    );
    Ok(delivered_count)
}
